// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.9.2-8-ga92ca9b"
#define MICROPY_GIT_HASH "a92ca9b"
#define MICROPY_BUILD_DATE "2020-03-01"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (9)
#define MICROPY_VERSION_MICRO (2)
#define MICROPY_VERSION_STRING "1.9.2"
