// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.9.2-v1.0.1-11-g76c2248-dirty"
#define MICROPY_GIT_HASH "76c2248-dirty"
#define MICROPY_BUILD_DATE "2020-03-05"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (9)
#define MICROPY_VERSION_MICRO (2)
#define MICROPY_VERSION_STRING "1.9.2"
